anguage: ruby
rvm:
  - 2.2.4
services:
  - postgresql
env:
  - RAILS_ENV=test
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
before_install:
  - psql -c 'create database strEAT_test;' -U postgres
deploy:
  provider: heroku
  api_key:
      secure: RFxdjAMZTQtoWZPxBVcQeP9gX4pd69ORnDIXZXkuRzuKUQlmn7aXdvmxKdKfWsYfcWl28/HaqZwUHPXDCq8r/SJaZmch708QA7WRADmtrw7VMxCGbHnzqNCUSEITYz4ENOd1lB8Ebqzl5VVpgtm4v7LLut3WI0J4uE13kStsUhb12aV2ShNYOEZbebVoETN4heGA45dDY1X5PNzlo5szHA+jmG539gOXizRS6mcYeIIQiiDP4dZNAEUrK7iWSI0LLho0HDyPoDq7NfhoM8IQZfHYZipZMeFwJLVSm9iWquqxcZ7qb7IrF+cHCr8X7A2ouV0XSUyoZ9VCZenxWkVsJ3FGVF1JsD5zE5+R3hmObE6JGFU3/EkCOU+wnCprbMI8g7//ccA6X1sKolh9FArsbuzFXQBvLfyhOyVKqF/p4674s1wcuNZa73Ku6j6sTI3cLGT4FEi79207wc63ti6cNrnh2TfU5VkEe+pPucU519jJNiBNgg8RLFOLJ3Tlyyj2SdS3n3fFfUwiGH/ThKKhZvea/+xkchGbGZLCDi96tpYoqEnVBrKHFZiGRHabQhz6gIOoIDvA4woJoPKrHkBetf/tCE/7gZpLLSFhsgf0T1/2YR7Jv/JUWDBIup0Wv1/T/NrupaLF1rzzgKNKZnvGb/PElTmQPTFsNUqnQxZWsKQ=
  app: streat

sudo: required
