# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cecd07f15d2fdd3c354761841eddae0efdf9f7e7095ebeb36f5718b71b097fa5dc582e7e8b1d3109e766bdd9bcdf08d0ad24f97e3e1a2e347ca5b7f15cc1b1f

test:
  secret_key_base: 614d56c8f744409b15b50c5e965aa8f4bbfac750282a42fe76c95c8836036b541eb755293049560430fd2d6a80b2e42f44134c73a59e84a0f5b9bf99b7a406d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
